-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")
-- Safer autocmd for image rendering
-- vim.api.nvim_create_autocmd("FileType", {
--   pattern = { "markdown" },
--   callback = function()
--     vim.keymap.set("n", "<CR>", function()
--       local ok, image = pcall(require, "image")
--       if ok and vim.fn.bufname() ~= "" then -- Only if buffer has a name/file
--         pcall(image.hijack_buffer)
--         pcall(image.render)
--       end
--     end, { buffer = true, desc = "Render images in markdown" })
--   end,
-- })
